/**
 * All 25 Tier I criteria, exactly as specified in the Northbridge Exit Standard.
 * Source: Tier I Final Build Directive v2.0 — Section V.
 * These are locked values and must not be modified without principal approval.
 */

export interface CriterionSeed {
  criterionId: string;       // G1C1 through G5C25
  gate: string;              // Full gate name
  gateWeight: number;        // 1.5 | 1.0 | 1.25
  criterionName: string;
  operatorQuestion: string;  // Exact question read to client
  score1Response: string;
  score2Response: string;
  score3Response: string;
  score4Response: string;
  transactionConsequence: string;
  dscrImpact: string;        // Low | Medium | Medium-High | High | Very High
  defaultSeverity: string;   // Critical | Weakness | Acceptable | Premium
  defaultPriority: string;   // Immediate | 90-Day | 12-Month | Monitor
  criticalCriterion: boolean;
}

export const CRITERIA_SEED: CriterionSeed[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // GATE 1 — AUTHORITY ARCHITECTURE  (weight 1.5x, max 30)
  // ═══════════════════════════════════════════════════════════════════════
  {
    criterionId: "G1C1",
    gate: "Gate 1 — Authority Architecture",
    gateWeight: 1.5,
    criterionName: "Decision Bottlenecking",
    operatorQuestion: "What percentage of non-routine operational choices require your specific approval before staff will act — and what happens to the business on a day you are unreachable?",
    score1Response: "Founder is the single decision node for virtually all non-routine choices. Staff habitually wait, text, or call before acting. Delay patterns are visible across daily operations. No documented authority exists at any threshold. Transaction consequence: Key-person risk is unmitigable under current structure. Buyer requires extended transition service agreement and continuity covenant. Lender requires personal guarantee without time limit. Multiple is at floor for the sector.",
    score2Response: "Founder approves most decisions above a low, informal threshold. Some staff act independently on routine matters but escalate frequently on any ambiguity. Delegation is personality-based, not documented or enforceable. Transaction consequence: LOI will include earn-out or escrow contingency tied to founder retention period. Buyer will probe staff in diligence interviews to test actual authority distribution and likely find gaps.",
    score3Response: "Decision rights are largely distributed and staff operate within understood authority lanes. Founder involvement is limited to defined thresholds and genuine exceptions. Some informal documentation exists. Transaction consequence: No material discount triggered. Buyer will verify through reference calls and one or two staff interviews. Passes standard diligence without contingency.",
    score4Response: "Decision rights are documented, tested, and independently verifiable. Staff can articulate their own authority in writing. A 30-day founder absence would not materially disrupt operations. Decision Rights Matrix exists and is actively used by the management team. Transaction consequence: Premium multiple supportable. Buyer diligence confirms independence through staff interviews. Lender waives continuity covenant.",
    transactionConsequence: "Key-person risk directly suppresses multiple and drives earn-out or escrow requirement proportional to the degree of founder dependency confirmed in diligence.",
    dscrImpact: "High",
    defaultSeverity: "Critical",
    defaultPriority: "Immediate",
    criticalCriterion: true,
  },
  {
    criterionId: "G1C2",
    gate: "Gate 1 — Authority Architecture",
    gateWeight: 1.5,
    criterionName: "Succession Continuity",
    operatorQuestion: "If you were unavailable for 90 days starting tomorrow — health event, family emergency, planned sabbatical — what happens operationally, and where is that plan written down?",
    score1Response: "No succession plan exists. No named successor. No documented knowledge transfer of any kind. Founder departure creates immediate operational crisis with no recovery mechanism. Transaction consequence: Lender requires key-person life and disability coverage as a loan condition. Buyer requires 18 to 24-month transition period with escrow holdback tied to demonstrated operational continuity. Deal structure is constrained before negotiation begins.",
    score2Response: "Informal understanding exists of who would step up but nothing is documented, tested, or funded. Named person may not be capable or willing to assume the role. No 30/60/90-day operating plan has been written or shared. Transaction consequence: Buyer conducts deep reference interviews on the named successor. Discount applied if successor competence is unverified. Earn-out is tied to operational stability in the post-close period.",
    score3Response: "Documented succession plan identifies roles and responsibilities for a 30 to 90-day transition scenario. Has not been formally tested but is credible given current staffing depth and organizational structure. Transaction consequence: Neutral. Buyer reviews the document, conducts one reference interview, and moves forward without material contingency.",
    score4Response: "Succession plan is documented, tested through real or simulated absence, and embedded in governance documentation. Named successors have demonstrated operational authority over a meaningful period. Transition is a planned event, not a crisis response. Transaction consequence: Reduces buyer transition risk pricing materially. Lender may waive continuity covenant. Shorter or no earn-out requirement. Supports multiple expansion.",
    transactionConsequence: "Absence of a tested succession plan requires extended transition periods and escrow structures that constrain deal economics before negotiation begins.",
    dscrImpact: "High",
    defaultSeverity: "Critical",
    defaultPriority: "Immediate",
    criticalCriterion: true,
  },
  {
    criterionId: "G1C3",
    gate: "Gate 1 — Authority Architecture",
    gateWeight: 1.5,
    criterionName: "Signature Authority Decentralization",
    operatorQuestion: "Who can sign contracts, execute vendor agreements, move material funds, and bind the business legally if you are not available — and where is that authority documented?",
    score1Response: "Founder holds all signature authority across all material categories — banking, contracts, vendor agreements, and legal commitments. No delegated authority is documented anywhere in the organization. Transaction consequence: Lender requires broad personal guarantee. Buyer's counsel flags concentration in reps and warranties review. Post-close operational continuity depends on legal intervention if founder is unavailable.",
    score2Response: "Some informal delegation exists but is not memorialized in banking resolutions, operating agreements, or authority matrices. Staff exercise de facto authority in limited circumstances without formal backing. Transaction consequence: Buyer's counsel flags the gap. Legal remediation required pre-close at seller's cost. Discount applied for operational risk.",
    score3Response: "Signature authority is documented in key categories with delegation to named staff or roles for defined thresholds. Banking resolutions and operating agreements reflect current practice. Transaction consequence: Neutral. Buyer confirms delegation structure through legal review without raising material concern.",
    score4Response: "Full decentralized authority structure is documented and current across all material categories — banking, contracts, vendor agreements, and spend thresholds. Authority matrix is filed, reviewed annually, and operationally tested. Transaction consequence: Reduces legal friction in the transition. Accelerates close process. Supports compressed or waived transition period.",
    transactionConsequence: "Concentrated signature authority creates legal risk in the transaction and requires lender and counsel remediation as a closing condition.",
    dscrImpact: "Medium",
    defaultSeverity: "Critical",
    defaultPriority: "Immediate",
    criticalCriterion: false,
  },
  {
    criterionId: "G1C4",
    gate: "Gate 1 — Authority Architecture",
    gateWeight: 1.5,
    criterionName: "Governance Maturity",
    operatorQuestion: "Is there a recurring management forum with documented outcomes and real external accountability — one that operates independently of you as the sole decision center?",
    score1Response: "No governance structure of any kind. No recurring management meetings with documented outcomes. Business runs entirely on founder instinct and informal conversation. No external accountability forum or advisor exists. Transaction consequence: Buyer sees no institutional operating evidence. Valuation based entirely on trailing financials with a heavy discount for operational risk. Management team premium is not awarded under any standard valuation methodology.",
    score2Response: "Informal management meetings occur but are irregular, undocumented, and founder-driven. No external accountability. Advisory relationships, if any, are social rather than substantive and produce no documented output. Transaction consequence: Buyer will not credit governance. Evidence is insufficient to support an institutional operating narrative. Management team premium is not awarded.",
    score3Response: "Regular management cadence exists with documented agendas and follow-up accountability. At least one external advisor or board member provides real, evidenced accountability that is not merely social. Transaction consequence: Neutral to positive. Buyer credits governance. Supports a credible management team narrative during diligence.",
    score4Response: "Formal governance framework with documented cadence, accountability structure, escalation rules, and substantive external oversight. Management team participates in decision-making and is held accountable through the structure independent of founder direction. Transaction consequence: Premium positioning. Supports management buyout optionality. Reduces buyer transition risk pricing. Compresses or eliminates earn-out requirement.",
    transactionConsequence: "Governance absence removes the management team premium from the valuation and signals to buyers that operational continuity cannot be demonstrated independently.",
    dscrImpact: "Medium",
    defaultSeverity: "Critical",
    defaultPriority: "Immediate",
    criticalCriterion: false,
  },
  {
    criterionId: "G1C5",
    gate: "Gate 1 — Authority Architecture",
    gateWeight: 1.5,
    criterionName: "Key Relationship Decentralization",
    operatorQuestion: "For your top ten clients and top five vendors — who is the primary day-to-day contact, and what happens to those relationships specifically if you exit the business?",
    score1Response: "Founder is the primary or sole relationship holder for the majority of top-10 clients and key vendors. Relationships are personal, informal, and non-transferable. Clients routinely refer to the business by the founder's name. Transaction consequence: Buyer will conduct client portability analysis and discover the personal-relationship dependency immediately. Revenue receives a significant transferability discount. Lender may apply concentration covenant as a financing condition.",
    score2Response: "Some non-founder contacts exist at the operational level but the founder is the primary relationship owner for most top clients and key vendors. Institutional backup is thin or informal. Transaction consequence: Buyer discounts revenue transferability. Earn-out tied to client retention post-close is structurally required. Discount applied for relationship risk.",
    score3Response: "Most client relationships have a non-founder primary contact for operational matters. Founder is a relationship sponsor but not the sole touchpoint for day-to-day service. Key vendors have documented contacts managed by operations staff. Transaction consequence: Neutral to mildly positive. Buyer confirms through client reference calls. Revenue receives partial transferability credit in the valuation model.",
    score4Response: "Client relationships are institutionalized. Clients interact primarily with account managers or operations staff. Founder operates at the sponsorship and escalation level only. Vendor relationships are managed by role, not by person. Transaction consequence: Supports full revenue transferability narrative in the CIM. Reduces earn-out pressure materially. Lender underwrites revenue as fully transferable.",
    transactionConsequence: "Personal relationship concentration creates revenue transferability risk that buyers price directly into the offer through earn-out, escrow, or discount structures.",
    dscrImpact: "High",
    defaultSeverity: "Critical",
    defaultPriority: "Immediate",
    criticalCriterion: true,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // GATE 2 — PROCESS INDEPENDENCE  (weight 1.0x, max 20)
  // ═══════════════════════════════════════════════════════════════════════
  {
    criterionId: "G2C6",
    gate: "Gate 2 — Process Independence",
    gateWeight: 1.0,
    criterionName: "SOP Accessibility and Daily Use",
    operatorQuestion: "Can a competent employee run your core workflows today without calling you — and where does that documentation live, who maintains it, and when was it last updated?",
    score1Response: "No documented SOPs exist for any critical workflow. Operations run entirely on verbal instruction, founder demonstration, and tribal knowledge held by one or two long-tenure employees. A key employee departure would trigger operational crisis immediately. Transaction consequence: Buyer cannot underwrite operating continuity. Deal is structured with extended transition requirement and employee retention bonuses at seller's expense as a closing condition.",
    score2Response: "Some documentation exists — in email threads, informal checklists, or a single employee's notes — but it is not standardized, actively maintained, or used consistently by the front line. Staff cannot rely on it when situations vary from the norm. Transaction consequence: Buyer tests SOP usability through direct staff interviews in diligence. Weak or decorative SOPs are flagged. Process independence credit is not awarded in the valuation.",
    score3Response: "Core workflows are documented in a usable format. Staff can execute critical processes without founder involvement in standard situations. Documentation is maintained, if imperfectly current, and is referenced when questions arise. Transaction consequence: Neutral to positive. Buyer confirms usability through staff interviews. Credit awarded for operating independence in the valuation model.",
    score4Response: "SOPs exist for all critical workflows, are current, formatted consistently, stored accessibly in a shared system, and demonstrably used by front-line staff daily. A new hire can execute core processes to 90% accuracy within a defined onboarding window without founder instruction. Transaction consequence: Accelerates diligence. Supports operating independence and scalability narrative in CIM. Reduces post-acquisition integration cost for buyer.",
    transactionConsequence: "Undocumented operations create post-acquisition operational risk that buyers price through extended transition requirements and employee retention bonuses at seller expense.",
    dscrImpact: "Medium-High",
    defaultSeverity: "Critical",
    defaultPriority: "Immediate",
    criticalCriterion: false,
  },
  {
    criterionId: "G2C7",
    gate: "Gate 2 — Process Independence",
    gateWeight: 1.0,
    criterionName: "Training Independence",
    operatorQuestion: "How long does it take to get a new employee to full productivity — and how much of that ramp depends on your personal involvement versus a documented system?",
    score1Response: "All training is founder-led. No training materials, onboarding documentation, or structured process exists anywhere in the organization. The founder is the institutional memory. New hires require months of direct founder instruction before reaching independent productivity. Transaction consequence: Buyer requires extended transition service agreement. Staffing risk is priced into the offer. Lender may require a continuity rider as a financing condition.",
    score2Response: "Some training materials exist but are incomplete and must be supplemented by direct instruction from the founder or a senior employee whose knowledge is not itself documented. Ramp time is long and founder-dependent. Transaction consequence: Buyer notes staffing risk. Discount applied for training dependency. Post-acquisition scaling assumptions are discounted in the financial model.",
    score3Response: "Structured onboarding and role-specific training exists. New hires reach productivity through documented materials and peer or supervisor-led process without founder involvement in most cases. Transaction consequence: Neutral. Buyer confirms through HR reference or staff interviews and raises no concern.",
    score4Response: "Training is fully systematized. Onboarding playbook, role-specific training modules, and performance ramp expectations are documented, tested, and consistently producing on-time productivity without any founder involvement. Transaction consequence: Supports scalability and post-acquisition integration narrative. Reduces buyer's post-close risk assessment. Accelerates management team confidence for a financial buyer.",
    transactionConsequence: "Founder-dependent training creates staffing risk that constrains post-acquisition scaling and extends the founder's required presence post-close.",
    dscrImpact: "Medium",
    defaultSeverity: "Critical",
    defaultPriority: "Immediate",
    criticalCriterion: false,
  },
  {
    criterionId: "G2C8",
    gate: "Gate 2 — Process Independence",
    gateWeight: 1.0,
    criterionName: "Exception Frequency and Founder Workarounds",
    operatorQuestion: "When something falls outside the normal process — an unusual client request, a vendor problem, a scheduling conflict — what actually happens, and how often does it come to you?",
    score1Response: "Founder workarounds are constant and expected by the entire staff. Employees routinely route exceptions directly to the founder rather than applying any documented escalation logic. Process documentation, where it exists, is decorative and not followed under pressure. Transaction consequence: Diligence interviews with staff will reveal this pattern immediately. Operating independence credit is zero. Buyer prices ongoing founder dependency directly into the deal structure.",
    score2Response: "Workarounds occur regularly but are recognized internally as a problem worth fixing. Some escalation logic exists but is inconsistently applied depending on the employee and situation. Founder involvement in exceptions is frequent enough to be structural rather than truly exceptional. Transaction consequence: Buyer notes the process maturity gap. Discount or extended transition requirement is applied in the offer.",
    score3Response: "Workarounds occur occasionally and follow a defined escalation path when they do arise. Founder involvement in process deviations is the exception, not the rule. Exceptions are tracked informally and reviewed periodically. Transaction consequence: Neutral. Buyer observes functional process discipline through staff interviews. No concern is raised.",
    score4Response: "Exceptions are rare, documented when they occur, and treated as process improvement inputs rather than one-off founder decisions. Process deviations trigger a defined review and update cycle. Workaround rate is measurable and demonstrably declining over time. Transaction consequence: Buyer sees a self-correcting operating system. Supports operating maturity narrative. Reduces post-acquisition integration risk.",
    transactionConsequence: "High exception routing to the founder confirms operational dependency that diligence will surface through staff interviews, directly suppressing operating independence credit.",
    dscrImpact: "Medium",
    defaultSeverity: "Critical",
    defaultPriority: "Immediate",
    criticalCriterion: false,
  },
  {
    criterionId: "G2C9",
    gate: "Gate 2 — Process Independence",
    gateWeight: 1.0,
    criterionName: "Quality Control Independence",
    operatorQuestion: "What is the last checkpoint before work goes to a client — and is the person doing that check someone other than you?",
    score1Response: "Founder is the effective QC standard for anything that materially affects a client or the business. No documented QC checkpoints exist at the staff level. Output quality depends on the founder's review before delivery. Transaction consequence: Buyer cannot underwrite operational continuity. Operating independence credit is zero. Buyer's investment thesis after acquisition requires founder's continued presence at current operating level.",
    score2Response: "Informal QC exists at the staff level but is inconsistently applied. Founder review remains the effective standard for anything that materially affects a client or the business. Staff QC is a first filter, not a final gate. Transaction consequence: Buyer notes the dependency. No credit for QC independence awarded. Post-acquisition scaling assumptions are discounted in the financial model.",
    score3Response: "Non-founder QC checkpoints exist for most standard deliverables. Staff have clear authority and accountability for output quality within defined parameters. Founder reviews genuine exceptions and complex cases only. Transaction consequence: Neutral to positive. Buyer confirms through operations interview. Credit for operating independence is awarded.",
    score4Response: "Full QC system is documented, role-assigned, and enforced across the operation. Founder is not part of the standard QC chain for any normal output. Error rates are tracked and quality standards are maintained independently. Transaction consequence: Supports operating independence and scalability narrative. Buyer can model post-acquisition growth without founder capacity constraint.",
    transactionConsequence: "Founder-dependent quality control creates capacity constraint that limits post-acquisition scalability and is flagged as operational risk in diligence.",
    dscrImpact: "Medium",
    defaultSeverity: "Weakness",
    defaultPriority: "90-Day",
    criticalCriterion: false,
  },
  {
    criterionId: "G2C10",
    gate: "Gate 2 — Process Independence",
    gateWeight: 1.0,
    criterionName: "Error Recurrence and Post-Mortem Discipline",
    operatorQuestion: "When something goes wrong operationally — a job failure, a client complaint, a billing error — what is the actual process, and how do you verify the same failure does not recur?",
    score1Response: "No post-mortem process of any kind exists. Errors are resolved by the founder personally through direct intervention, and the organization learns nothing from the event. The same operational failures recur on a predictable cycle. Transaction consequence: Buyer will identify recurring failure patterns in diligence through staff interviews. Operational risk premium is applied. Management team credibility is materially undermined.",
    score2Response: "Post-mortems occur informally after significant failures but are founder-driven, undocumented, and rarely produce enforceable process changes that persist beyond the immediate event. Transaction consequence: Buyer notes the absence of improvement infrastructure. No credit for operational learning discipline is awarded in the valuation.",
    score3Response: "Post-mortem process exists for significant operational failures. Root causes are identified and process changes are documented. Recurrence rate is measurable and trending downward. Transaction consequence: Neutral. Buyer observes an improving operating system through the record of process changes. No concern is raised in diligence.",
    score4Response: "Systematic post-mortem discipline is embedded in the operating cadence. All significant errors trigger a documented review, root cause analysis, and process update that is tracked for recurrence. Transaction consequence: Supports operating maturity narrative. Reduces buyer's post-acquisition integration risk. Demonstrates institutional learning capability.",
    transactionConsequence: "Recurring operational failures without documented remediation signal operational immaturity that buyers discount in the valuation model.",
    dscrImpact: "Medium",
    defaultSeverity: "Critical",
    defaultPriority: "Immediate",
    criticalCriterion: false,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // GATE 3 — COMMERCIAL DISCIPLINE  (weight 1.0x, max 20)
  // ═══════════════════════════════════════════════════════════════════════
  {
    criterionId: "G3C11",
    gate: "Gate 3 — Commercial Discipline",
    gateWeight: 1.0,
    criterionName: "Pricing Guardrails",
    operatorQuestion: "How do you determine what to charge for a given job or engagement — and is there a documented floor below which a proposal simply cannot be approved?",
    score1Response: "Pricing is entirely intuition-based across the business. No floor, no formula, no margin constraint of any kind. The founder prices each job based on feel, relationship, and perceived market tolerance. Gross margin variance is high and unexplained across comparable work categories. Transaction consequence: Buyer cannot underwrite forward margin with confidence. EBITDA normalization is contested throughout the QoE process. Multiple compression is material and reflects commercial instability. Lender haircuts forward earnings projection.",
    score2Response: "Informal pricing conventions exist — 'we usually charge around X for this type of job' — but they are not documented, not enforced, and regularly bypassed for preferred clients or competitive pressure situations. Transaction consequence: Buyer identifies margin inconsistency in the financial review. Discount applied for commercial instability. Normalized EBITDA falls below seller's expectation at closing.",
    score3Response: "Documented pricing model or rate structure exists. Margin floors are defined for standard work categories. Exceptions require some form of documented approval before the proposal goes out. Transaction consequence: Neutral. Buyer verifies pricing documentation and confirms floor compliance through a sample transaction review.",
    score4Response: "Pricing is fully systematized. Formula-based margin floor, documented exceptions process, and historical compliance tracking all exist. Staff can generate accurate quotes within the system without founder input for all standard work categories. Transaction consequence: Supports forward margin underwriting. Reduces buyer commercial risk. Lender projects forward earnings with confidence. No haircut applied for pricing variability.",
    transactionConsequence: "Intuition-based pricing creates margin variance that QoE will exploit, compressing EBITDA and reducing the multiple applied to forward earnings.",
    dscrImpact: "High",
    defaultSeverity: "Critical",
    defaultPriority: "Immediate",
    criticalCriterion: true,
  },
  {
    criterionId: "G3C12",
    gate: "Gate 3 — Commercial Discipline",
    gateWeight: 1.0,
    criterionName: "Discounting Authority and Logic",
    operatorQuestion: "Who can approve a discount, what is the maximum they can approve without escalation, and where is that policy written down and enforced?",
    score1Response: "No discount policy exists anywhere in the business. Founder approves all discounts informally, frequently, and without any documentation or audit trail. Discount rates are inconsistent and often material relative to the underlying job margin. Transaction consequence: QoE will identify discount leakage in the margin analysis. Every undocumented add-back is contested by buyer's accountant. Adjusted EBITDA falls materially below seller's expectation. Lender haircuts forward earnings.",
    score2Response: "Informal discount norms exist but are not enforced. Some staff apply discounts without approval at their discretion. Founder often retroactively approves undocumented discounts. Transaction consequence: Buyer identifies systematic margin leakage. Discount applied in the offer for commercial undiscipline. Normalized margin is lower than seller's operating assumption.",
    score3Response: "Discount policy is documented and includes threshold authority levels by role. Material discounts require written approval before the proposal is issued. Policy is known by the relevant staff and applied consistently in most situations. Transaction consequence: Neutral. Buyer reviews the policy and verifies compliance through a sample transaction review.",
    score4Response: "Discount authority is formally structured, role-assigned, logged in the CRM or approval system, and auditable by anyone reviewing the records. Exception rate and discount frequency are tracked as explicit management metrics reviewed monthly. Transaction consequence: Supports margin quality narrative. Reduces earnings recast risk in QoE. No discount leakage identified in financial review.",
    transactionConsequence: "Undocumented discount patterns create QoE exposure that reduces the defensibility of normalized EBITDA and compresses the multiple applied at closing.",
    dscrImpact: "High",
    defaultSeverity: "Critical",
    defaultPriority: "Immediate",
    criticalCriterion: false,
  },
  {
    criterionId: "G3C13",
    gate: "Gate 3 — Commercial Discipline",
    gateWeight: 1.0,
    criterionName: "Contractual Revenue Protection",
    operatorQuestion: "What percentage of your revenue this year is covered by a current, signed agreement — and do those agreements contain assignment provisions that survive a change of ownership?",
    score1Response: "Majority of revenue is transactional, verbal, or governed by expired or unsigned agreements. Client relationships are informal and personal. No enforceable assignment provisions exist in any material agreement in the business. Transaction consequence: Revenue transferability is severely compromised. Buyer will not credit informal revenue at full multiple. Escrow and earn-out structures are near-certain. Buyer's counsel requires contract remediation as a hard closing condition.",
    score2Response: "Some revenue has contract coverage but agreements are inconsistent in quality — often expired, missing key provisions, or executed through informal emails rather than executed documents. Transaction consequence: Buyer's counsel flags contract quality throughout diligence. Cleanup is required pre-close at seller's cost. Discount applied to the unprotected revenue portion in the valuation.",
    score3Response: "Most material revenue has current, signed agreements with standard protection provisions. Contract quality is acceptable at this tier. Some gaps exist in smaller or older accounts. Transaction consequence: Neutral. Buyer reviews sample agreements and confirms coverage of material revenue. No material flagging in the legal review.",
    score4Response: "Revenue is majority protected by institutional-grade agreements — MSAs, evergreen contracts, or multi-year commitments with assignment and renewal provisions that survive a change of control. Contract database is organized, current, and can be produced for diligence within 48 hours. Transaction consequence: Supports full revenue transferability narrative in CIM. Reduces buyer revenue risk. Compresses earn-out requirement.",
    transactionConsequence: "Unprotected revenue creates assignability risk at closing that triggers escrow, earn-out, and contract remediation requirements that directly reduce net proceeds.",
    dscrImpact: "High",
    defaultSeverity: "Weakness",
    defaultPriority: "90-Day",
    criticalCriterion: false,
  },
  {
    criterionId: "G3C14",
    gate: "Gate 3 — Commercial Discipline",
    gateWeight: 1.0,
    criterionName: "Sales Process Independence",
    operatorQuestion: "Can your team identify, qualify, propose, and close new business without your direct involvement — and where is that process documented?",
    score1Response: "Founder is the sole revenue producer. All meaningful business development, proposal preparation, and closing activity requires the founder's direct involvement. No structured sales process exists for any non-founder staff. Transaction consequence: Revenue is entirely founder-dependent. Buyer cannot underwrite forward revenue without a long-term founder commitment built into the deal structure. Earn-out tied directly to founder-generated revenue is structurally required.",
    score2Response: "Some non-founder sales activity occurs but the process is informal and results are inconsistent. Founder closes all material deals. CRM, if it exists, functions as the founder's personal contact list rather than an organizational pipeline tool. Transaction consequence: Buyer discounts forward revenue assumptions. Extended earn-out tied to founder performance is the likely offer structure.",
    score3Response: "A defined sales process exists with documented stage logic. Staff manage leads, advance pipeline, and close standard-tier work without founder involvement. Founder involvement is reserved for complex or unusually large accounts. Transaction consequence: Neutral. Buyer confirms sales process independence through staff interviews and CRM review.",
    score4Response: "Sales function is fully institutionalized. Pipeline is managed in CRM with defined stage logic and measurable conversion rates by stage. Non-founder staff close across the full revenue range of the business. Founder operates as a relationship sponsor, not a revenue producer. Transaction consequence: Revenue is fully transferable. Supports full multiple on forward earnings. Buyer can model post-acquisition growth without founder dependency.",
    transactionConsequence: "Founder-dependent revenue generation creates forward earnings risk that buyers structure as earn-out, directly reducing upfront value received at closing.",
    dscrImpact: "Very High",
    defaultSeverity: "Critical",
    defaultPriority: "Immediate",
    criticalCriterion: true,
  },
  {
    criterionId: "G3C15",
    gate: "Gate 3 — Commercial Discipline",
    gateWeight: 1.0,
    criterionName: "Customer Economics Visibility",
    operatorQuestion: "Without waiting for month-end close, can you tell me right now what the net margin was on the last three jobs or engagements you completed?",
    score1Response: "No job or customer economics visibility exists at any meaningful level. Gross revenue is tracked but net margin per engagement is unknown until month-end accounting — if it is ever calculated at the engagement level. Pricing decisions are made without economics feedback of any kind. Transaction consequence: Buyer cannot underwrite unit economics. Multiple is based on blended revenue with a heavy risk premium. Operating leverage thesis is entirely unsupported.",
    score2Response: "Some job costing exists but it is inconsistent, often completed well after the fact, and not routinely used to inform pricing or operational decisions. Economics data is theoretically available but practically unused in the business. Transaction consequence: Buyer notes the absence of real-time economics discipline. Discount applied for commercial operating weakness.",
    score3Response: "Job or customer economics are tracked with reasonable consistency. Margin per engagement is reviewable on an acceptable lag and is used in operational and pricing decisions by management. Transaction consequence: Neutral. Buyer reviews sample economics data, confirms the methodology, and moves on without concern.",
    score4Response: "Real-time or near-real-time customer and job economics are visible to management through an integrated job costing or CRM system. Margin by service line, customer, and geography is actively tracked and used in pricing and operational decisions. Transaction consequence: Supports operating leverage narrative. Buyer can model unit economics with confidence. Reduces multiple compression risk from margin uncertainty.",
    transactionConsequence: "Absence of job-level economics removes the operating leverage narrative from the buyer's valuation model and suppresses the multiple applied to forward earnings.",
    dscrImpact: "Medium",
    defaultSeverity: "Weakness",
    defaultPriority: "90-Day",
    criticalCriterion: false,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // GATE 4 — REVENUE QUALITY & DURABILITY  (weight 1.5x, max 30)
  // ═══════════════════════════════════════════════════════════════════════
  {
    criterionId: "G4C16",
    gate: "Gate 4 — Revenue Quality & Durability",
    gateWeight: 1.5,
    criterionName: "Customer Concentration",
    operatorQuestion: "What percentage of your total revenue comes from your single largest client — and what is the nature of that relationship in terms of contract coverage and relationship ownership?",
    score1Response: "A single client or small cluster represents more than 30% of annual revenue without contractual protection, and the relationship is personally held by the founder with no institutional backup. Transaction consequence: Severe concentration risk. SBA lenders decline or require aggressive escrow structures where concentration exceeds 25% in a single customer. Strategic buyers apply escrow or earn-out tied directly to client retention post-close. Multiple compression is material and non-negotiable in the offer.",
    score2Response: "Concentration exists in the 15 to 30% range, or exists below 15% but is unprotected by contract and the relationship is clearly founder-personal with no secondary contact at the client. Transaction consequence: Buyer models concentration risk into the offer model. Discount or contingency structure applied. Lender may require a formal concentration covenant as a financing condition.",
    score3Response: "No single client exceeds 15% of revenue, or concentration exists but is protected by a current contract and the relationship is institutionalized at the account management level with a non-founder primary contact. Transaction consequence: Neutral. Buyer reviews the customer list, confirms distribution, and moves on without concern.",
    score4Response: "Revenue is well-diversified across a broad client base. No single client exceeds 10% of annual revenue. Top clients are under current contracts, managed day-to-day by non-founder staff, and show strong multi-year retention track records. Transaction consequence: Supports premium multiple. Reduces earn-out pressure materially. Lender underwrites revenue without a concentration covenant.",
    transactionConsequence: "Customer concentration above 25% creates SBA financing barriers and earn-out requirements that are structurally non-negotiable regardless of other deal terms.",
    dscrImpact: "Very High",
    defaultSeverity: "Critical",
    defaultPriority: "Immediate",
    criticalCriterion: true,
  },
  {
    criterionId: "G4C17",
    gate: "Gate 4 — Revenue Quality & Durability",
    gateWeight: 1.5,
    criterionName: "Revenue Mix and Durability",
    operatorQuestion: "What percentage of your revenue this year comes from clients or agreements that were already in place at the start of the year — versus new business you had to actively go earn this year?",
    score1Response: "Revenue is almost entirely transactional in nature. No recurring agreements, no retainers, and no contracts governing ongoing work. Revenue must be re-earned from scratch each period through active founder-led effort and is inherently unpredictable. Transaction consequence: Buyer applies transactional revenue discount in valuation. Forward earnings projections are contested in every QoE review. Multiple is at the floor for the sector. Revenue transferability is the single largest valuation risk.",
    score2Response: "A small percentage of revenue is recurring in any meaningful sense. Most revenue is project or transaction-based and depends on active sales effort each period. Transaction consequence: Buyer discounts forward revenue. Earn-out tied to post-close revenue performance is the likely offer structure.",
    score3Response: "A meaningful portion of revenue — 30% or more — is governed by recurring agreements or established service contracts with a documented renewal history over multiple periods. Transaction consequence: Neutral to positive. Buyer gives partial recurring revenue credit. No material discount applied for the revenue mix.",
    score4Response: "Majority of revenue is recurring, contracted, or governed by MSAs with auto-renewal provisions and a multi-year retention track record. Revenue is predictable, independently verifiable, and fully transferable under a change of ownership. Transaction consequence: Recurring revenue multiple applies. Lender underwrites forward earnings with confidence. Earn-out requirement compresses or is eliminated.",
    transactionConsequence: "Transactional revenue creates forward earnings uncertainty that buyers discount through lower multiples and earn-out structures tied to revenue performance post-close.",
    dscrImpact: "High",
    defaultSeverity: "Critical",
    defaultPriority: "Immediate",
    criticalCriterion: false,
  },
  {
    criterionId: "G4C18",
    gate: "Gate 4 — Revenue Quality & Durability",
    gateWeight: 1.5,
    criterionName: "Owner-Identity Decoupling",
    operatorQuestion: "If you were no longer associated with this business, would your clients stay — and is that because of the company's capabilities and reputation, or because of you personally?",
    score1Response: "The founder is the brand. Clients refer to the business by the founder's name. Marketing, proposals, and all client communications are built around the founder's personal identity. Revenue retention without the founder is untested and highly uncertain under any reasonable scenario. Transaction consequence: Brand transfer value is near zero. Goodwill premium is not awarded. Extended founder stay is required and priced into the offer. Buyer views this as a personal service business, not a transferable enterprise.",
    score2Response: "Brand has some independent identity but remains heavily associated with the founder. Key clients mention the founder by name as the primary reason they chose and stay with the business. Transaction consequence: Buyer conducts client portability interviews. Earn-out tied to founder retention period is structurally standard. Discount applied for brand dependency.",
    score3Response: "Brand has a meaningful independent market presence. Website, reputation, and client relationships are company-facing rather than founder-facing. Some clients are founder-loyal but the majority are company-loyal by observable behavior. Transaction consequence: Neutral. Buyer credits brand independence partially. Shorter earn-out requirement. Goodwill credit awarded at standard rates.",
    score4Response: "Brand is fully decoupled from founder identity. Company has an independent reputation, digital presence, and market position that exists and operates without reference to the founder. Clients buy from the company brand, not the founder personally. Transaction consequence: Full goodwill credit awarded. Brand premium supports higher multiple. Short or no earn-out required.",
    transactionConsequence: "Founder-brand fusion suppresses goodwill credit and requires extended founder presence post-close that buyers price as a discount to the enterprise value.",
    dscrImpact: "High",
    defaultSeverity: "Critical",
    defaultPriority: "Immediate",
    criticalCriterion: true,
  },
  {
    criterionId: "G4C19",
    gate: "Gate 4 — Revenue Quality & Durability",
    gateWeight: 1.5,
    criterionName: "Lead Generation System",
    operatorQuestion: "Where did your last ten new clients actually come from — and how many of those sources operate without your direct personal involvement?",
    score1Response: "All meaningful new business originates from the founder's personal network, referrals that come to the founder personally, or the founder's direct sales activity. No systematized lead generation channel exists that operates independently. Transaction consequence: Buyer will not credit pipeline value without a long-term founder commitment built into the deal structure. Forward revenue is discounted to reflect single-source dependency.",
    score2Response: "Some non-founder lead generation occurs — basic digital presence, informal referral tracking — but it is inconsistent, unmeasured, and not systematized into a repeatable process. Transaction consequence: Buyer discounts the forward pipeline. No credit for lead generation independence is awarded.",
    score3Response: "Defined lead generation channels exist that operate independently of the founder. CRM pipeline is maintained with basic stage logic. Lead sources are tracked and producing a consistent if modest volume of opportunities. Transaction consequence: Neutral. Buyer confirms channel diversity and reviews pipeline data without raising concern.",
    score4Response: "Multi-channel lead generation system is documented, measured, and producing a consistent pipeline volume independent of any founder activity. CRM stage logic is defined, pipeline velocity is tracked, and conversion rates by source are reported regularly to management. Transaction consequence: Supports forward revenue underwriting. Buyer can model post-acquisition growth without founder dependency. Revenue upside thesis is credible.",
    transactionConsequence: "Founder-dependent lead generation creates forward revenue uncertainty that suppresses the multiple applied to projected earnings and drives earn-out requirements.",
    dscrImpact: "Medium-High",
    defaultSeverity: "Weakness",
    defaultPriority: "90-Day",
    criticalCriterion: false,
  },
  {
    criterionId: "G4C20",
    gate: "Gate 4 — Revenue Quality & Durability",
    gateWeight: 1.5,
    criterionName: "Contract Enforceability and Assignability",
    operatorQuestion: "If the business were sold today, would your client agreements transfer automatically to a new owner — or would you need to return to each client individually for re-approval or re-negotiation?",
    score1Response: "Client relationships are primarily governed by verbal agreements or informal email chains. No current, properly executed agreements exist for material client relationships. Assignment clauses, if any exist in any document, are absent or unenforceable under a change of control. Transaction consequence: Buyer's counsel flags every material client relationship. Revenue is subject to renegotiation post-close without any legal protection. Buyer will not close without significant escrow protection or full contract remediation. This is a deal-stopper condition in every institutional transaction.",
    score2Response: "Some agreements exist but are outdated, missing standard key provisions, or inconsistently executed across the client base. Assignment provisions are absent or untested. Transaction consequence: Buyer requires pre-close remediation of material agreements at seller's cost and time. Discount or escrow applied for the coverage gaps that remain at closing.",
    score3Response: "Most material client relationships have current, signed agreements with standard provisions and operative assignment clauses. Some gaps exist in smaller or legacy accounts. Transaction consequence: Neutral. Buyer reviews sample agreements, confirms coverage of material revenue, and moves forward without concern on the primary revenue base.",
    score4Response: "All material revenue is governed by institutional-grade contracts with clear assignment provisions that survive a change of control. Contract database is organized and producible for diligence within 48 hours. Transaction consequence: Revenue transfers cleanly. No pre-close remediation required. Supports full multiple on revenue in the valuation.",
    transactionConsequence: "Unenforceable or non-assignable contracts create a legal closing condition that exposes material revenue to post-close renegotiation and generates escrow requirements.",
    dscrImpact: "Very High",
    defaultSeverity: "Critical",
    defaultPriority: "Immediate",
    criticalCriterion: true,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // GATE 5 — FINANCIAL INTEGRITY  (weight 1.25x, max 25)
  // ═══════════════════════════════════════════════════════════════════════
  {
    criterionId: "G5C21",
    gate: "Gate 5 — Financial Integrity",
    gateWeight: 1.25,
    criterionName: "Reporting Cadence and Close Discipline",
    operatorQuestion: "When do your monthly financial statements actually close — and when are those statements in a state where you would rely on them for a real business decision?",
    score1Response: "Financial reporting is irregular, frequently delinquent, and founder-driven rather than process-driven. P&L may be available quarterly or annually but not on a reliable monthly basis. Statements are produced for tax purposes rather than management purposes. Transaction consequence: Buyer cannot perform trailing twelve-month analysis without full reconstruction. Accountant remediation fees become a hard closing condition at seller's expense. Lender requires CPA-reviewed or audited statements as a financing condition.",
    score2Response: "Monthly financials are produced but inconsistently timed — often available two or three weeks after month close — and frequently require adjustment before they can be used reliably for management or transaction analysis. Transaction consequence: Buyer applies quality-of-earnings discount. Lender may require reviewed statements. Diligence timeline extends to accommodate the reconstruction work.",
    score3Response: "Monthly close occurs within a consistent window, generally by the 15th of the following month. Statements are reliable, reconciled, and actively used in operational decision-making by management. Transaction consequence: Neutral. Buyer uses statements as primary financial evidence without requiring reconstruction or remediation.",
    score4Response: "Monthly close discipline is tight and consistent — statements are closed and reviewed by the 10th of every month. Financial reporting is a business instrument used actively in management, not a compliance afterthought. Transaction consequence: Supports quality-of-earnings narrative. Reduces lender underwriting friction. Accelerates diligence timeline materially.",
    transactionConsequence: "Irregular financial reporting requires reconstruction work that extends diligence timelines and generates accountant fees charged to the seller as a closing condition.",
    dscrImpact: "High",
    defaultSeverity: "Critical",
    defaultPriority: "Immediate",
    criticalCriterion: false,
  },
  {
    criterionId: "G5C22",
    gate: "Gate 5 — Financial Integrity",
    gateWeight: 1.25,
    criterionName: "Normalization Integrity",
    operatorQuestion: "How many personal or owner-related expenses are currently running through the business P&L — and can you produce a contemporaneous written record supporting each adjustment you would expect a buyer to give you credit for?",
    score1Response: "Personal and owner-related expenses are deeply embedded throughout the P&L — vehicle costs, personal insurance, family member compensation, travel, and discretionary expenses are mixed with legitimate business costs and are not separately tracked or documented anywhere. Transaction consequence: QoE process will be adversarial. Buyer's accountant will haircut every undocumented add-back. Adjusted EBITDA is contested at every step and falls materially below seller's expectation. Deal pricing and structure fully reflect the uncertainty.",
    score2Response: "Owner-related expenses exist but are partially identifiable. Some categories are mixed with legitimate business costs and supporting documentation is incomplete or relies on memory rather than contemporaneous records. Add-back support is thin. Transaction consequence: QoE surfaces multiple unverifiable add-backs. Buyer discounts contested amounts. Normalized EBITDA is materially lower than seller's starting negotiating position.",
    score3Response: "Owner-related expenses are largely identifiable and separable from legitimate business costs. Normalization is straightforward for most categories. Some cleanup may be required but the process is not adversarial and the adjustments are reasonable in scope. Transaction consequence: Neutral. QoE produces clean adjusted EBITDA without significant dispute or time-consuming reconstruction.",
    score4Response: "Normalization is clean and pre-organized before the transaction process begins. Owner compensation is at market rate or cleanly documented where above-market. Personal expenses are absent from the P&L or cleanly segregated with contemporaneous documentation supporting every add-back without requiring reconstruction. Transaction consequence: Adjusted EBITDA is instantly defensible. Supports higher multiple and accelerates lender underwriting. QoE process is brief and non-adversarial.",
    transactionConsequence: "Undocumented owner add-backs create an adversarial QoE process that reduces normalized EBITDA and compresses the multiple applied to the adjusted earnings.",
    dscrImpact: "Very High",
    defaultSeverity: "Critical",
    defaultPriority: "Immediate",
    criticalCriterion: true,
  },
  {
    criterionId: "G5C23",
    gate: "Gate 5 — Financial Integrity",
    gateWeight: 1.25,
    criterionName: "DSCR Safety Margin",
    operatorQuestion: "After normalizing your financials and replacing your compensation with a market-rate equivalent for your operating role, what is your debt service coverage ratio — and is it above 1.5x on a trailing basis?",
    score1Response: "DSCR is below 1.25x on a normalized basis. Existing debt service consumes the majority of normalized cash flow, leaving no meaningful headroom for acquisition financing at any reasonable loan-to-value. Transaction consequence: SBA and conventional lenders decline or require a significant equity injection that reduces buyer pool. Buyer pool is limited to cash purchasers or sellers willing to carry significant seller financing. Deal structure is severely constrained before negotiation begins.",
    score2Response: "DSCR is in the 1.25x to 1.5x range on a normalized basis. Technically supportable but leaves limited headroom for acquisition debt at standard underwriting parameters. Transaction consequence: Lender applies conservative underwriting assumptions throughout. Buyer's required equity contribution is elevated. Acquisition financing is constrained, which reduces the effective buyer pool and suppresses offer pricing.",
    score3Response: "DSCR exceeds 1.5x on a normalized basis. Acquisition financing is supportable under standard SBA or conventional lender underwriting without unusual structure or equity requirements. Transaction consequence: Neutral. Standard acquisition financing is available. Full buyer pool is accessible at normal equity requirements.",
    score4Response: "DSCR exceeds 2.0x on a normalized basis with meaningful headroom above that threshold. Strong cash flow coverage provides confidence for acquisition debt at competitive terms. Transaction consequence: Full acquisition financing is available at competitive terms. Lender competition is possible. Supports higher purchase price financing. Reduces required equity contribution for a buyer materially.",
    transactionConsequence: "DSCR below SBA thresholds constrains the available buyer pool to cash purchasers and seller-financing structures that reduce the effective sale price.",
    dscrImpact: "Very High",
    defaultSeverity: "Critical",
    defaultPriority: "Immediate",
    criticalCriterion: true,
  },
  {
    criterionId: "G5C24",
    gate: "Gate 5 — Financial Integrity",
    gateWeight: 1.25,
    criterionName: "Internal Controls",
    operatorQuestion: "Is there anyone other than you who reviews and approves significant payments, disbursements, and financial commitments before they are executed — and is that process documented?",
    score1Response: "Founder has sole authority over all financial activity across the business. No second-signer requirement, no disbursement review process, no separation of duties in any material financial category. Transaction consequence: Buyer's QoE will flag internal control weakness as a formal finding in the diligence report. Lender may require controls installation as a hard closing condition. Audit risk premium is applied to the valuation.",
    score2Response: "Some informal controls exist — accounting staff processes payments but founder approves everything — but separation of duties is incomplete and no documented control procedures exist in writing. Transaction consequence: Buyer notes the control weakness in diligence. Not a deal-killer in most cases but creates friction and adds to transition risk pricing in the offer.",
    score3Response: "Material disbursements above a defined threshold require documented approval from a second person. Separation of duties exists between the initiator and the approver for key financial categories. Transaction consequence: Neutral. Buyer confirms controls through the accounting interview. No flagging in the diligence report.",
    score4Response: "Documented internal control framework exists with defined approval thresholds, clear separation of duties, and second-signer requirements across all material financial activity. Controls are evidenced in the accounting record and can be demonstrated to a buyer's accountant during diligence. Transaction consequence: Supports QoE narrative. Reduces audit risk premium. Accelerates lender approval timeline.",
    transactionConsequence: "Internal control weakness generates a formal QoE finding that lenders may require remediation of as a financing condition, extending the diligence timeline.",
    dscrImpact: "High",
    defaultSeverity: "Critical",
    defaultPriority: "Immediate",
    criticalCriterion: false,
  },
  {
    criterionId: "G5C25",
    gate: "Gate 5 — Financial Integrity",
    gateWeight: 1.25,
    criterionName: "Audit and Data Room Readiness",
    operatorQuestion: "If a serious buyer requested a complete data room tomorrow — three years of clean, reconciled financials, entity documents, key contracts, and core operating records — how long would it actually take you to produce it?",
    score1Response: "Financial records are disorganized, incomplete, or scattered across disconnected locations, personal computers, and email threads. A complete data room request would require weeks of reconstruction work before anything could be shared. Historical statements may not reconcile to the tax returns. Transaction consequence: Buyer loses confidence during the diligence process. In any competitive process, an organized buyer walks and a disorganized seller does not close. This single finding has killed transactions at LOI stage before any negotiation begins.",
    score2Response: "Records exist but are not organized for third-party review in their current state. Significant effort over multiple weeks would be required to produce a complete and coherent data room. Transaction consequence: Diligence timeline extends materially. Buyer absorbs reconstruction cost into the offer price. A trust discount is applied by every serious counterparty who reviews the state of the records.",
    score3Response: "Records are reasonably organized and a coherent data room could be assembled within approximately one week with moderate effort. Core financial records are complete and reconciled for the last three fiscal years. Transaction consequence: Neutral. Buyer proceeds on a standard diligence timeline without requiring seller to extend or pay for reconstruction.",
    score4Response: "Data room architecture is pre-built or substantially pre-organized. Three years of reconciled records are categorized, labeled, and accessible in a shared drive structure that can be permissioned to a buyer immediately. A complete and organized data room is producible within 48 hours of a request. Transaction consequence: Accelerates diligence, compresses timeline, reduces buyer risk perception, and signals institutional operating maturity to every counterparty who receives the link. Supports premium pricing narrative directly.",
    transactionConsequence: "Data room disorganization creates a trust deficit at the LOI stage that competitive buyers use to walk or apply a trust discount that reduces net proceeds.",
    dscrImpact: "High",
    defaultSeverity: "Critical",
    defaultPriority: "Immediate",
    criticalCriterion: false,
  },
];

/** Ordered list of all 25 criterion IDs for validation */
export const ALL_CRITERION_IDS = CRITERIA_SEED.map(c => c.criterionId);

/** Group criteria by gate for display */
export const CRITERIA_BY_GATE = CRITERIA_SEED.reduce<Record<string, CriterionSeed[]>>(
  (acc, c) => {
    const key = c.gate;
    if (!acc[key]) acc[key] = [];
    acc[key].push(c);
    return acc;
  },
  {}
);

/** Gate metadata */
export const GATE_META = [
  { name: "Gate 1 — Authority Architecture", weight: 1.5, max: 30, code: "G1" },
  { name: "Gate 2 — Process Independence",   weight: 1.0, max: 20, code: "G2" },
  { name: "Gate 3 — Commercial Discipline",  weight: 1.0, max: 20, code: "G3" },
  { name: "Gate 4 — Revenue Quality & Durability", weight: 1.5, max: 30, code: "G4" },
  { name: "Gate 5 — Financial Integrity",    weight: 1.25, max: 25, code: "G5" },
] as const;
